# Generated by Django 3.2.5 on 2022-07-06 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(max_length=255)),
                ('initial_state', models.CharField(max_length=255)),
                ('interim_state', models.CharField(max_length=255)),
                ('final_state', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('sign', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workflowitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('initial_state', models.CharField(max_length=50)),
                ('interim_state', models.CharField(max_length=50)),
                ('final_state', models.CharField(max_length=50)),
                ('action', models.CharField(blank=True, max_length=25, null=True)),
                ('subaction', models.CharField(blank=True, max_length=55, null=True)),
                ('previous_action', models.CharField(blank=True, max_length=55, null=True)),
                ('model_type', models.CharField(max_length=55)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(blank=True, default=True, null=True)),
                ('event_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venzoscf.transitionmanager')),
            ],
            options={
                'verbose_name_plural': 'WorkFlowItem',
            },
        ),
        migrations.CreateModel(
            name='workevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(default='DRAFT', max_length=50)),
                ('action', models.CharField(blank=True, max_length=25, null=True)),
                ('subaction', models.CharField(blank=True, max_length=55, null=True)),
                ('to_state', models.CharField(default='DRAFT', max_length=50)),
                ('interim_state', models.CharField(default='DRAFT', max_length=50)),
                ('end_value', models.CharField(blank=True, max_length=55, null=True)),
                ('is_read', models.BooleanField(blank=True, default=True, null=True)),
                ('final_value', models.CharField(blank=True, max_length=55, null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=55)),
                ('event_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workitems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflowevent', to='venzoscf.workflowitems')),
            ],
            options={
                'verbose_name_plural': 'WorkFlowEvent',
            },
        ),
    ]
