# Generated by Django 3.2.5 on 2022-07-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venzoscf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Action',
            },
        ),
        migrations.AlterModelOptions(
            name='transitionmanager',
            options={'verbose_name_plural': '1. TransitionManager'},
        ),
        migrations.AlterModelOptions(
            name='workevents',
            options={'verbose_name_plural': '3. WorkFlowEvent'},
        ),
        migrations.AlterModelOptions(
            name='workflowitems',
            options={'verbose_name_plural': '2. WorkFlowItem'},
        ),
        migrations.RenameField(
            model_name='transitionmanager',
            old_name='sign',
            new_name='sign_required',
        ),
        migrations.RemoveField(
            model_name='transitionmanager',
            name='action',
        ),
        migrations.RemoveField(
            model_name='transitionmanager',
            name='interim_state',
        ),
    ]
