# Generated by Django 3.2.5 on 2022-07-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venzoscf', '0002_auto_20220712_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionmanager',
            name='sub_sign',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
