# Generated by Django 3.2.5 on 2022-07-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venzoscf', '0003_transitionmanager_sub_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitionmanager',
            name='sub_sign',
            field=models.IntegerField(default=0),
        ),
    ]
