# Generated by Django 3.2.5 on 2022-07-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venzoscf', '0005_alter_transitionmanager_sub_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowitems',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venzoscf.transitionmanager'),
        ),
    ]
