a = [
    "AWAITING_SIGN_A",
    "AWAITING_SIGN_B",
    "AWAITING_SIGN_C",
    "AWAITING_SIGN_D",
    "AWAITING_SIGN_E",
    "AWAITING_SIGN_F",
    "AWAITING_SIGN_G",
    "AWAITING_SIGN_H",
    "AWAITING_SIGN_I",
    "AWAITING_SIGN_J",
    "AWAITING_SIGN_K",
    "AWAITING_SIGN_L",
]